_name_or_path:
    value: distilbert-base-cased
_wandb:
    value:
        cli_version: 0.27.0
        e:
            sdejdegry4b3s9jy13omm0came9pti1b:
                apple:
                    ecpuCores: 6
                    gpuCores: 8
                    macModel: Mac16,12
                    memoryGb: 16
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "4294967296"
                codePath: train_with_wandb.py
                codePathLocal: train_with_wandb.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "245107195904"
                        used: "100298964992"
                email: g25ait2048@iitj.ac.in
                executable: /Users/karansingh/Assingments/MLOPs/ASS2/.venv/bin/python3
                host: KARANs-MacBook-Air.local
                memory:
                    total: "17179869184"
                os: macOS-26.3.1-arm64-arm-64bit
                program: /Users/karansingh/Assingments/MLOPs/ASS2/train_with_wandb.py
                python: CPython 3.11.15
                root: /Users/karansingh/Assingments/MLOPs/ASS2
                startedAt: "2026-05-20T09:00:16.381206Z"
                writerId: sdejdegry4b3s9jy13omm0came9pti1b
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.11.15
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 71
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 71
            "3":
                - 2
                - 7
                - 13
                - 16
                - 19
                - 62
                - 66
            "4": 3.11.15
            "5": 0.27.0
            "6": 5.8.1
            "9":
                "1": transformers_trainer
            "12": 0.27.0
            "13": darwin-arm64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
activation:
    value: gelu
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
architectures:
    value:
        - DistilBertForMaskedLM
attention_dropout:
    value: 0.1
auto_find_batch_size:
    value: false
average_tokens_across_devices:
    value: true
batch_eval_metrics:
    value: false
batch_size:
    value: 16
bf16:
    value: false
bf16_full_eval:
    value: false
bos_token_id:
    value: null
chunk_size_feed_forward:
    value: 0
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 0
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
dataset:
    value: UCSD Goodreads
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_static_graph:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
deepspeed:
    value: null
dim:
    value: 768
disable_tqdm:
    value: false
do_eval:
    value: true
do_predict:
    value: false
do_train:
    value: false
dropout:
    value: 0.1
dtype:
    value: float32
enable_jit_checkpoint:
    value: false
eos_token_id:
    value: null
epochs:
    value: 3
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: null
eval_strategy:
    value: epoch
eval_use_gather_object:
    value: false
fp16:
    value: false
fp16_full_eval:
    value: false
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
full_determinism:
    value: false
gradient_accumulation_steps:
    value: 1
gradient_checkpointing:
    value: false
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: false
hidden_dim:
    value: 3072
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: null
hub_revision:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
        "2": LABEL_2
        "3": LABEL_3
        "4": LABEL_4
        "5": LABEL_5
        "6": LABEL_6
        "7": LABEL_7
ignore_data_skip:
    value: false
include_for_metrics:
    value: []
include_num_input_tokens_seen:
    value: "no"
initializer_range:
    value: 0.02
is_encoder_decoder:
    value: false
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
        LABEL_2: 2
        LABEL_3: 3
        LABEL_4: 4
        LABEL_5: 5
        LABEL_6: 6
        LABEL_7: 7
learning_rate:
    value: 3e-05
length_column_name:
    value: length
liger_kernel_config:
    value: null
load_best_model_at_end:
    value: true
local_rank:
    value: -1
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: results_wandb/logs
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 50
logging_strategy:
    value: steps
lr_scheduler_kwargs:
    value: null
lr_scheduler_type:
    value: linear
max_grad_norm:
    value: 1
max_length:
    value: 512
max_position_embeddings:
    value: 512
max_steps:
    value: -1
metric_for_best_model:
    value: loss
model:
    value: distilbert-base-cased
model/num_parameters:
    value: 65787656
model_type:
    value: distilbert
n_heads:
    value: 12
n_layers:
    value: 6
neftune_noise_alpha:
    value: null
num_train_epochs:
    value: 3
optim:
    value: adamw_torch_fused
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: results_wandb
output_hidden_states:
    value: false
output_past:
    value: true
pad_token_id:
    value: 0
parallelism_config:
    value: null
per_device_eval_batch_size:
    value: 32
per_device_train_batch_size:
    value: 16
prediction_loss_only:
    value: false
problem_type:
    value: null
project:
    value: huggingface
push_to_hub:
    value: false
qa_dropout:
    value: 0.1
remove_unused_columns:
    value: true
report_to:
    value:
        - wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
run_name:
    value: distilbert-wandb-run
save_on_each_node:
    value: false
save_only_model:
    value: false
save_steps:
    value: 500
save_strategy:
    value: epoch
save_total_limit:
    value: null
seed:
    value: 42
seq_classif_dropout:
    value: 0.2
sinusoidal_pos_embds:
    value: false
skip_memory_metrics:
    value: true
tf32:
    value: null
tie_weights_:
    value: true
tie_word_embeddings:
    value: true
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_empty_cache_steps:
    value: null
trackio_bucket_id:
    value: null
trackio_space_id:
    value: null
trackio_static_space_id:
    value: null
train_sampling_strategy:
    value: random
transformers_version:
    value: 5.8.1
use_cache:
    value: false
use_cpu:
    value: false
use_liger_kernel:
    value: false
vocab_size:
    value: 28996
warmup_ratio:
    value: null
warmup_steps:
    value: 100
weight_decay:
    value: 0.01
